name: CI

on:
  push:
    branches:
      - 'logicmonitor-main'
      - 'main'
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Test
      run: |
        dotnet test -r testcoverage --collect:"XPlat Code Coverage"  -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
        ls
        cp ./testcoverage/*/coverage.info ./
        pwd
        cd ./testcoverage
        ls
        
        
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ${{ github.workspace }}/testcoverage/lcov.info
